### ISSUE TITLE
[Backend/Cloud] Look into whether or not we can reduce cloudwatch costs

### ISSUE THREAD

**Issue by bennypc** [ubc-biztech/serverless-biztechapp#351]
Description: Currently paying the most for cloudwatch out of all AWS expenses. See if there's anyway we can reduce the amount we spend on cloudwatch by doing some research. You can access the AWS console with login details found on notion

**Comment by voctory** [comment]
@bennypc @AllanT102 100% of the costs are coming from automatically-created alarms for DynamoDB tables. Did anyone depend on CloudWatch _alarms_ last year for anything? Is someone being notified for alarms? If no one is using alarms, I can delete most of them.

I'll attach a report later.

**Comment by AllanT102** [comment]
Just saw this sorry @voctory I dont think we ever touched the alarms. Maybe it'd be good to keep them on the tables w high read/writes but otherwise I think it's a good catch. Feel free to delete!

**Comment by voctory** [comment]
Report on cost optimizations here, addresses both CloudWatch and DynamoDB: https://www.notion.so/ubcbiztech/Dev-AWS-CloudWatch-DynamoDB-Cost-Optimizations-d3054d5461264355b9e87b9277bda361?pvs=4

I'll be switching all tables to On-Demand and monitoring costs over the next few days to confirm expected behaviour. Previously table capacities are listed in the Appendix in case we need to revert.
